"""Reporting module — aggregate results into structured reports."""

from __future__ import annotations

import json
import os
import platform
import shlex
from datetime import datetime
from pathlib import Path
from typing import Any

from cmd2 import with_default_category

import utils.run_task as rt
import utils.string_format as sf
from utils.base_shell import BaseShell

PLATFORM_SYSTEM = platform.system()


def _gather_process_logs(results_root: Path) -> list[dict[str, Any]]:
    processes = results_root / "processes"
    if not processes.exists():
        return []
    records = []
    for json_path in sorted(processes.glob("*.json"), reverse=True):
        try:
            data = json.loads(json_path.read_text(encoding="utf-8"))
            records.append(data)
        except (OSError, json.JSONDecodeError):
            continue
    return records


def _build_markdown_report(records: list[dict[str, Any]], target: str, author: str) -> str:
    lines = []
    lines.append(f"# Netspion Security Assessment Report")
    lines.append(f"")
    lines.append(f"**Target:** {target}")
    lines.append(f"**Author:** {author}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Platform:** {platform.system()} {platform.release()}")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## Executive Summary")
    lines.append(f"")
    lines.append(f"This report contains the results of automated security assessments")
    lines.append(f"performed using Netspion ethical hacking suite.")
    lines.append(f"")
    lines.append(f"## Task Summary")
    lines.append(f"")
    lines.append(f"| Task ID | Command | Status | Return Code |")
    lines.append(f"|---------|---------|--------|-------------|")

    for rec in records:
        cmd = shlex.join(rec.get("command", []))
        status = rec.get("status", "unknown")
        rc = rec.get("returncode", "N/A")
        lines.append(f"| {rec.get('task_id', '?')} | `{cmd[:60]}` | {status} | {rc} |")

    lines.append(f"")
    lines.append(f"## Detailed Results")
    lines.append(f"")

    for rec in records:
        task_id = rec.get("task_id", "?")
        cmd = shlex.join(rec.get("command", []))
        status = rec.get("status", "unknown")
        stdout_path = rec.get("stdout_path", "")
        stderr_path = rec.get("stderr_path", "")

        lines.append(f"### Task: {task_id}")
        lines.append(f"")
        lines.append(f"- **Command:** `{cmd}`")
        lines.append(f"- **Status:** {status}")
        lines.append(f"- **Mode:** {rec.get('mode', '?')}")
        lines.append(f"- **PID:** {rec.get('pid', '?')}")

        if stdout_path and os.path.exists(stdout_path):
            with open(stdout_path, "r", errors="replace") as f:
                content = f.read().strip()
            if content:
                lines.append(f"")
                lines.append(f"**stdout:**")
                lines.append(f"```")
                lines.append(content[:2000])
                if len(content) > 2000:
                    lines.append("... (truncated)")
                lines.append(f"```")

        if stderr_path and os.path.exists(stderr_path):
            with open(stderr_path, "r", errors="replace") as f:
                content = f.read().strip()
            if content:
                lines.append(f"")
                lines.append(f"**stderr:**")
                lines.append(f"```")
                lines.append(content[:1000])
                if len(content) > 1000:
                    lines.append("... (truncated)")
                lines.append(f"```")

        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

    lines.append(f"## Tools Used")
    lines.append(f"")
    for rec in records:
        cmd = shlex.join(rec.get("command", []))
        tool = cmd.split()[0] if cmd else "unknown"
        lines.append(f"- {tool}")

    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Report generated by Netspion*")

    return "\n".join(lines)


@with_default_category("Main commands")
class ReportingShell(BaseShell):
    def __init__(self):
        super().__init__("Reporting", "Report Generation")
        self.target = "undefined"
        self.author = "analyst"
        self.add_settable(cmd2.Settable("target", str, "Target name for report", self))
        self.add_settable(cmd2.Settable("author", str, "Author name for report", self))
        os.makedirs(self.resultsPath, exist_ok=True)
        self.do_help("-v")

    def do_generate_report(self, arg):
        "Generate a Markdown report from all task logs"
        records = _gather_process_logs(rt.get_results_root())
        if not records:
            print(sf.warning("No process records found. Run some tools first."))
            return
        md = _build_markdown_report(records, self.target, self.author)
        out = f"{self.resultsPath}report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        with open(out, "w", encoding="utf-8") as f:
            f.write(md)
        print(sf.success(f"Report saved: {out}"))

    def do_list_logs(self, arg):
        "List all available task logs"
        processes = rt.get_results_root() / "processes"
        if not processes.exists():
            print(sf.warning("No logs directory found."))
            return
        files = sorted(processes.glob("*.json"), reverse=True)
        for f_path in files[:50]:
            try:
                data = json.loads(f_path.read_text(encoding="utf-8"))
                print(f"  {data.get('task_id','?'):50s} {data.get('status','?'):12s} {data.get('pid','?'):>6}")
            except Exception:
                continue

    def do_export_csv(self, arg):
        "Export task log to CSV"
        records = _gather_process_logs(rt.get_results_root())
        if not records:
            print(sf.warning("No records found."))
            return
        out = f"{self.resultsPath}tasks_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        with open(out, "w", encoding="utf-8") as f:
            f.write("task_id,pid,status,returncode,started_at,command\n")
            for rec in records:
                cmd = shlex.join(rec.get("command", [])).replace('"', '""')
                f.write(f'{rec.get("task_id","")},{rec.get("pid","")},{rec.get("status","")},'
                        f'{rec.get("returncode","")},{rec.get("started_at","")},"{cmd}"\n')
        print(sf.success(f"CSV exported: {out}"))


def main():
    ReportingShell().cmdloop()
